name: "Validate and Release"

on:
  push:
    tags:
      - "release"
  workflow_dispatch:

jobs:
  validate:
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v3"
      - uses: "home-assistant/actions/hassfest@master"
      - uses: "hacs/action@main"
        with:
          category: "integration"

  create-release:
    needs: validate
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        
      - name: Get version from manifest
        id: manifest_version
        run: |
          VERSION=$(grep '"version":' custom_components/tartunlp_tts/manifest.json | cut -d'"' -f4)
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Generate Release Notes
        id: release_notes
        run: |
          echo "NOTES<<EOF" >> $GITHUB_OUTPUT
          echo "# Tartu NLP TTS ${{ steps.manifest_version.outputs.version }}" >> $GITHUB_OUTPUT
          echo "" >> $GITHUB_OUTPUT
          echo "## Muudatused" >> $GITHUB_OUTPUT
          echo "- Väljalase versioonile ${{ steps.manifest_version.outputs.version }}" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          name: "v${{ steps.manifest_version.outputs.version }}"
          tag_name: "v${{ steps.manifest_version.outputs.version }}"
          body: ${{ steps.release_notes.outputs.NOTES }}
          draft: false
          prerelease: false
          token: ${{ secrets.GITHUB_TOKEN }}