name: "Validate, Version Bump and Release"

on: 
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"

jobs:
  validate:
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v3"
      - uses: "home-assistant/actions/hassfest@master"
      - uses: "hacs/action@main"
        with:
          category: "integration"

  bump-and-release:
    # needs: validate  # Ootab valideerimise lõppu
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          
      - name: Get version from tag
        id: tag_version
        run: |
          VERSION=${GITHUB_REF#refs/tags/v}
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          
      - name: Update manifest.json
        run: |
          sed -i "s/\"version\": \".*\"/\"version\": \"${{ steps.tag_version.outputs.version }}\"/" custom_components/tartunlp_tts/manifest.json
          
      - name: Commit changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add custom_components/tartunlp_tts/manifest.json
          git commit -m "Bump version to ${{ steps.tag_version.outputs.version }}"
          git push

      - name: Generate Release Notes
        id: release_notes
        run: |
          echo "NOTES<<EOF" >> $GITHUB_OUTPUT
          echo "# Tartu NLP TTS ${{ steps.tag_version.outputs.version }}" >> $GITHUB_OUTPUT
          echo "" >> $GITHUB_OUTPUT
          echo "## Muudatused" >> $GITHUB_OUTPUT
          echo "- Väljalase versioonile ${{ steps.tag_version.outputs.version }}" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          body: ${{ steps.release_notes.outputs.NOTES }}
          draft: false
          prerelease: false
          token: ${{ secrets.GITHUB_TOKEN }}